In [ ]:
#importing the necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
#loading the dataset
df = pd.read_csv('california_housing_dataset.csv')
df

### Analyzing the data

In [254]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 16860 entries, 0 to 16859
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   MedInc      16860 non-null  float64
 1   HouseAge    16860 non-null  float64
 2   AveRooms    16860 non-null  float64
 3   AveBedrms   16860 non-null  float64
 4   Population  16860 non-null  float64
 5   AveOccup    16860 non-null  float64
 6   Latitude    16860 non-null  float64
 7   Longitude   16860 non-null  float64
 8   target      16860 non-null  float64
dtypes: float64(9)
memory usage: 1.2 MB

In [253]:
df.describe()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,target
count,16860.000000,16860.00000,16860.000000,16860.000000,16860.000000,16860.000000,16860.000000,16860.000000,16860.000000
mean,3.638751,28.42153,5.247849,0.720620,7.021978,1.349140,35.515958,-119.459949,1.014055
std,1.455294,11.89691,1.140977,0.036948,0.663992,0.165435,2.087352,1.929903,0.327197
min,0.499900,1.00000,2.018458,0.623278,1.386294,0.767529,32.540000,-124.350000,0.139753
25%,2.601600,19.00000,4.516864,0.698591,6.731018,1.249298,33.970000,-121.470000,0.757998
50%,3.529600,29.00000,5.226737,0.717156,7.063904,1.339664,34.250000,-118.500000,0.983575
75%,4.411850,36.00000,5.881800,0.738218,7.416378,1.443884,37.640000,-118.080000,1.252763
max,8.023600,52.00000,8.477813,0.806653,8.050065,1.714743,41.950000,-114.310000,1.757341

### Removing the outliers

In [256]:
from scipy import stats
df_clean = df.copy()
for col in df.columns:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    df_clean[col] = df[col].clip(lower, upper)
df_clean.describe()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,target
count,16860.000000,16860.00000,16860.000000,16860.000000,16860.000000,16860.000000,16860.000000,16860.000000,16860.000000
mean,3.622363,28.42153,5.238609,0.720271,7.051083,1.349807,35.515958,-119.459949,1.014055
std,1.410982,11.89691,1.106956,0.035363,0.563526,0.163663,2.087352,1.929903,0.327197
min,0.499900,1.00000,2.469461,0.639150,5.702978,0.957420,32.540000,-124.350000,0.139753
25%,2.601600,19.00000,4.516864,0.698591,6.731018,1.249298,33.970000,-121.470000,0.757998
50%,3.529600,29.00000,5.226737,0.717156,7.063904,1.339664,34.250000,-118.500000,0.983575
75%,4.411850,36.00000,5.881800,0.738218,7.416378,1.443884,37.640000,-118.080000,1.252763
max,7.127225,52.00000,7.929203,0.797659,8.050065,1.714743,41.950000,-114.310000,1.757341

## Dealing with missing values

In [ ]:
df.isnull().sum()

In [ ]:
#Using median imputation
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='median') 
df_imputed = pd.DataFrame(
    imputer.fit_transform(df_clean),
    columns=df_clean.columns
)
df = df_imputed
df

In [ ]:
df.isnull().sum()

In [257]:
df.corr()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,target
MedInc,1.000000,-0.179454,0.560893,-0.217699,0.045922,-0.019560,-0.075489,-0.010264,0.627812
HouseAge,-0.179454,1.000000,-0.247077,-0.122769,-0.206581,0.002941,0.005557,-0.095348,0.044975
AveRooms,0.560893,-0.247077,1.000000,0.175803,-0.073392,-0.002378,0.128710,-0.060170,0.212432
AveBedrms,-0.217699,-0.122769,0.175803,1.000000,-0.025526,-0.113259,0.064246,0.005638,-0.139392
Population,0.045922,-0.206581,-0.073392,-0.025526,1.000000,0.189077,-0.126808,0.092675,0.049961
AveOccup,-0.019560,0.002941,-0.002378,-0.113259,0.189077,1.000000,-0.145931,0.153237,-0.230150
Latitude,-0.075489,0.005557,0.128710,0.064246,-0.126808,-0.145931,1.000000,-0.799652,-0.170100
Longitude,-0.010264,-0.095348,-0.060170,0.005638,0.092675,0.153237,-0.799652,1.000000,-0.029178
target,0.627812,0.044975,0.212432,-0.139392,0.049961,-0.230150,-0.170100,-0.029178,1.000000

#### There are no parameters with really high collinearity so we will not drop any column

### Checking  multicollinearity to see if we can drop any column

In [ ]:

plt.figure(figsize=(12,8))
sns.heatmap(df.corr(),annot=True)

In [ ]:
sns.pairplot(df)

In [ ]:
sns.histplot(df['target'])

### We will remove the abnormal spikes

In [ ]:
print(df.skew())
print(df.corr()['target'].sort_values())

In [ ]:

for i in ["Population","AveBedrms","AveOccup"]:
    df[i]= np.log1p(df[i])

In [ ]:
#Checking if there is a need of applyiing log on "MedInc"
fig, axes = plt.subplots(1, 2, figsize=(12, 4))

axes[0].scatter(df['MedInc'], df['target'], alpha=0.1)
axes[0].set_title('Original MedInc vs Target')

axes[1].scatter(np.log1p(df['MedInc']), df['target'], alpha=0.1)
axes[1].set_title('Log MedInc vs Target')

In [ ]:

df = df[(df['target'] < 4.8)]  # catches the upper spike
df = df[np.abs(df['target'] -1.795)> 0.05 ]
df = df.reset_index(drop=True)

print(len(df))
sns.histplot(df['target'])

In [ ]:
df['target'].value_counts()

### Improving the symmetry of the graph

In [ ]:
# Making the curve more symmetric
df['target']= np.log1p(df['target'])
sns.histplot(df['target'])

In [ ]:
df.to_csv("cleaned_housing_dataset.csv",index=False)